var dataprotection=`
<p><span style="font-size:20pt;">Privacy Policy</span></p>
<h2><span style="font-size:16pt;">1. Data protection at a glance</span></h2>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">General information</span></h3>
<p><span style="font-size:11pt;">The following information provides a simple overview of what happens to your personal data when you visit this website. Personal data is all data with which you can be personally identified. You can find detailed information on the subject of data protection in our data protection declaration listed under this text.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Data collection on this website</span></h3>
<h4><span style="color:#666666;font-size:12pt;">Who is responsible for data collection on this website?</span></h4>
<p><span style="font-size:11pt;">The data processing on this website is carried out by the website operator. You can find his contact details in the section &quot;Information on the responsible party&quot; in this data protection declaration.</span></p>
<h4><span style="color:#666666;font-size:12pt;">How do we collect your data?</span></h4>
<p><span style="font-size:11pt;">On the one hand, your data is collected when you communicate it to us. This may, for example, be data that you enter in a contact form.</span></p>
<p><span style="font-size:11pt;">Other data is collected automatically or with your consent when you visit the website by our IT systems. This is primarily technical data (e.g. Internet browser, operating system or time of page access). This data is collected automatically as soon as you enter this website.</span></p>
<h4><span style="color:#666666;font-size:12pt;">What do we use your data for?</span></h4>
<p><span style="font-size:11pt;">Some of the data is collected to ensure that the website is provided without errors. Other data can be used to analyze your user behavior.</span></p>
<h4><span style="color:#666666;font-size:12pt;">What rights do you have regarding your data?</span></h4>
<p><span style="font-size:11pt;">You have the right to obtain information about the origin, recipient and purpose of your stored personal data free of charge at any time. You also have the right to request that this data be corrected or deleted. If you have given your consent to data processing, you can revoke this consent at any time for the future. You also have the right to request that the processing of your personal data be restricted under certain circumstances. You also have the right to lodge a complaint with the responsible supervisory authority.</span></p>
<p><span style="font-size:11pt;">You can contact us at any time with any questions about this or other issues relating to data protection.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Analysis tools and third-party tools</span></h3>
<p><span style="font-size:11pt;">When you visit this website, your surfing behavior may be statistically evaluated. This is done primarily with so-called analysis programs.</span></p>
<p><span style="font-size:11pt;">Detailed information about these analysis programs can be found in the following privacy policy.</span></p>
<h2><span style="font-size:16pt;">2. Hosting</span></h2>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">External hosting</span></h3>
<p><span style="font-size:11pt;">This website is hosted by an external service provider (hoster). The personal data collected on this website is stored on the hoster&apos;s servers. This may include IP addresses, contact requests, meta and communication data, contract data, contact details, names, website accesses and other data generated via a website.</span></p>
<p><span style="font-size:11pt;">The hoster is used for the purpose of fulfilling the contract with our potential and existing customers (Art. 6 Para. 1 lit. b GDPR) and in the interest of a secure, fast and efficient provision of our online offer by a professional provider (Art. 6 Para. 1 lit. f GDPR). If a corresponding consent has been requested, the processing is carried out exclusively on the basis of Art. 6 Para. 1 lit. a GDPR and Section 25 Para. 1 TTDSG, insofar as the consent includes the storage of cookies or access to information in the user&apos;s end device (e.g. device fingerprinting) within the meaning of the TTDSG. The consent can be revoked at any time.</span></p>
<p><span style="font-size:11pt;">Our host will only process your data to the extent necessary to fulfill its service obligations and will follow our instructions regarding this data.</span></p>
<p><span style="font-size:11pt;">We use the following hoster:</span></p>
<p><span style="font-size:11pt;">OVH GmbH</span><span style="font-size:11pt;"><br></span><span style="font-size:11pt;"><br></span><span style="font-size:11pt;"><br></span><span style="font-size:11pt;">Christophstra&szlig;e 19,</span><span style="font-size:11pt;"><br></span><span style="font-size:11pt;">50670 Cologne</span><span style="font-size:11pt;"><br></span><span style="font-size:11pt;">Germany</span></p>
<h2><span style="font-size:16pt;">3. General information and mandatory information</span></h2>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">data protection</span></h3>
<p><span style="font-size:11pt;">The operators of these pages take the protection of your personal data very seriously. We treat your personal data confidentially and in accordance with the statutory data protection regulations and this data protection declaration.</span></p>
<p><span style="font-size:11pt;">When you use this website, various personal data is collected. Personal data is data with which you can be personally identified. This privacy policy explains which data we collect and what we use it for. It also explains how and for what purpose this is done.</span></p>
<p><span style="font-size:11pt;">We would like to point out that data transmission over the Internet (e.g. when communicating by email) can have security gaps. Complete protection of data against access by third parties is not possible.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Note on the responsible body</span></h3>
<p><span style="font-size:11pt;">The responsible body for data processing on this website is:</span></p>
<p><span style="font-size:11pt;">BooM Investment GmbH</span><span style="font-size:11pt;"><br></span><span style="font-size:11pt;">Karpfenweg 1</span><span style="font-size:11pt;"><br></span><span style="font-size:11pt;">76189 Karlsruhe</span></p>
<p><span style="font-size:11pt;">Phone: 01734383864</span><span style="font-size:11pt;"><br></span><span style="font-size:11pt;">Email: info@boom-investment.de</span></p>
<p><span style="font-size:11pt;">The responsible body is the natural or legal person who alone or jointly with others decides on the purposes and means of processing personal data (e.g. names, e-mail addresses, etc.).</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Storage period</span></h3>
<p><span style="font-size:11pt;">Unless a more specific storage period has been specified in this data protection declaration, your personal data will remain with us until the purpose for data processing no longer applies. If you make a legitimate request for deletion or revoke your consent to data processing, your data will be deleted unless we have other legally permissible reasons for storing your personal data (e.g. retention periods under tax or commercial law); in the latter case, deletion will take place once these reasons no longer apply.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">General information on the legal basis for data processing on this website</span></h3>
<p><span style="font-size:11pt;">If you have consented to data processing, we will process your personal data on the basis of Art. 6 Para. 1 lit. a GDPR or Art. 9 Para. 2 lit. a GDPR if special categories of data are processed in accordance with Art. 9 Para. 1 GDPR. In the case of express consent to the transfer of personal data to third countries, data processing will also be carried out on the basis of Art. 49 Para. 1 lit. a GDPR. If you have consented to the storage of cookies or to access information on your end device (e.g. via device fingerprinting), data processing will also be carried out on the basis of Section 25 Para. 1 TTDSG. Consent can be revoked at any time. If your data is required to fulfill the contract or to carry out pre-contractual measures, we will process your data on the basis of Art. 6 Para. 1 lit. b GDPR. Furthermore, we process your data if it is required to fulfill a legal obligation on the basis of Art. 6 Para. 1 lit. c GDPR. Data processing may also be carried out on the basis of our legitimate interest in accordance with Art. 6 (1) (f) GDPR. The relevant legal bases in each individual case are explained in the following paragraphs of this data protection declaration.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Note on data transfer to the USA and other third countries</span></h3>
<p><span style="font-size:11pt;">Among other things, we use tools from companies based in the USA or other third countries that are not secure in terms of data protection law. If these tools are active, your personal data can be transferred to these third countries and processed there. We would like to point out that a level of data protection comparable to that in the EU cannot be guaranteed in these countries. For example, US companies are obliged to release personal data to security authorities without you as the data subject being able to take legal action against this. It cannot therefore be ruled out that US authorities (e.g. secret services) will process, evaluate and permanently store your data on US servers for surveillance purposes. We have no influence on these processing activities.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Revocation of your consent to data processing</span></h3>
<p><span style="font-size:11pt;">Many data processing operations are only possible with your express consent. You can revoke your consent at any time. The legality of the data processing carried out up to the time of revocation remains unaffected by the revocation.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Right to object to data collection in special cases and to direct advertising (Art. 21 GDPR)</span></h3>
<p><span style="font-size:11pt;">IF THE DATA PROCESSING IS CARRIED OUT ON THE BASIS OF ART. 6 PARAGRAPH 1 LIT. E OR F GDPR, YOU HAVE THE RIGHT TO OBJECT TO THE PROCESSING OF YOUR PERSONAL DATA AT ANY TIME FOR REASONS ARISING FROM YOUR PARTICULAR SITUATION; THIS ALSO APPLIES TO PROFILING BASED ON THESE PROVISIONS. THE RESPECTIVE LEGAL BASIS ON WHICH ANY PROCESSING IS BASED CAN BE FOUND IN THIS PRIVACY POLICY. IF YOU OBJECT, WE WILL NO LONGER PROCESS YOUR PERSONAL DATA UNLESS WE CAN PROVE COMPELLING LEGITIMATE GROUNDS FOR THE PROCESSING WHICH OVERRIDE YOUR INTERESTS, RIGHTS AND FREEDOMS OR THE PROCESSING IS FOR THE PURPOSE OF ASSERTING, EXERCISING OR DEFENDING LEGAL CLAIMS (OBJECTION ACCORDING TO ART. 21 PARA. 1 GDPR).</span></p>
<p><span style="font-size:11pt;">IF YOUR PERSONAL DATA IS PROCESSED FOR THE PURPOSE OF DIRECT MARKETING, YOU HAVE THE RIGHT TO OBJECT AT ANY TIME TO THE PROCESSING OF PERSONAL DATA CONCERNING YOU FOR THE PURPOSE OF SUCH ADVERTISING; THIS ALSO APPLIES TO PROFILING IN SO FAR AS IT IS RELATED TO SUCH DIRECT MARKETING. IF YOU OBJECT, YOUR PERSONAL DATA WILL SUBSEQUENTLY NO LONGER BE USED FOR THE PURPOSE OF DIRECT MARKETING (OBJECTION ACCORDING TO ART. 21 PARA. 2 GDPR).</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Right to lodge a complaint with the competent supervisory authority</span></h3>
<p><span style="font-size:11pt;">In the event of violations of the GDPR, those affected have the right to lodge a complaint with a supervisory authority, in particular in the Member State of their habitual residence, place of work or place of the alleged violation. The right to lodge a complaint is without prejudice to other administrative or judicial remedies.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Right to data portability</span></h3>
<p><span style="font-size:11pt;">You have the right to have data that we process automatically on the basis of your consent or in fulfillment of a contract handed over to you or to a third party in a common, machine-readable format. If you request that the data be transferred directly to another responsible party, this will only be done if it is technically feasible.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">SSL or TLS encryption</span></h3>
<p><span style="font-size:11pt;">For security reasons and to protect the transmission of confidential content, such as orders or inquiries that you send to us as the website operator, this site uses SSL or TLS encryption. You can recognize an encrypted connection by the fact that the address line of the browser changes from &quot;http://&quot; to &quot;https://&quot; and by the lock symbol in your browser line.</span></p>
<p><span style="font-size:11pt;">If SSL or TLS encryption is activated, the data you send to us cannot be read by third parties.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Information, deletion and correction</span></h3>
<p><span style="font-size:11pt;">Within the framework of the applicable legal provisions, you have the right at any time to obtain free information about your stored personal data, its origin and recipient and the purpose of data processing and, if applicable, a right to correction or deletion of this data. You can contact us at any time with this or other questions on the subject of personal data.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Right to restriction of processing</span></h3>
<p><span style="font-size:11pt;">You have the right to request that the processing of your personal data be restricted. You can contact us at any time to do so. The right to restrict processing exists in the following cases:</span></p>
<ul>
    <li style="list-style-type:disc;font-size:11pt;">
        <p><span style="font-size:11pt;">If you dispute the accuracy of your personal data stored by us, we usually need time to check this. For the duration of the check, you have the right to request that the processing of your personal data be restricted.</span></p>
    </li>
    <li style="list-style-type:disc;font-size:11pt;">
        <p><span style="font-size:11pt;">If the processing of your personal data was/is unlawful, you can request the restriction of data processing instead of deletion.</span></p>
    </li>
    <li style="list-style-type:disc;font-size:11pt;">
        <p><span style="font-size:11pt;">If we no longer need your personal data, but you require it to exercise, defend or assert legal claims, you have the right to request that the processing of your personal data be restricted instead of deleted.</span></p>
    </li>
    <li style="list-style-type:disc;font-size:11pt;">
        <p><span style="font-size:11pt;">If you have lodged an objection in accordance with Art. 21 Para. 1 GDPR, a balance must be struck between your interests and ours. As long as it is not yet clear whose interests prevail, you have the right to request that the processing of your personal data be restricted.</span></p>
    </li>
</ul>
<p><span style="font-size:11pt;">If you have restricted the processing of your personal data, these data may - with the exception of storage - only be processed with your consent or for the establishment, exercise or defense of legal claims or to protect the rights of another natural or legal person or for reasons of important public interest of the European Union or a Member State.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Objection to advertising emails</span></h3>
<p><span style="font-size:11pt;">The use of contact data published as part of the imprint obligation to send unsolicited advertising and information materials is hereby prohibited. The operators of the pages expressly reserve the right to take legal action in the event of unsolicited advertising information being sent, for example through spam emails.</span></p>
<h2><span style="font-size:16pt;">4. Data collection on this website</span></h2>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Cookies</span></h3>
<p><span style="font-size:11pt;">Our websites use so-called &quot;cookies&quot;. Cookies are small text files and do not cause any damage to your device. They are either stored temporarily for the duration of a session (session cookies) or permanently (permanent cookies) on your device. Session cookies are automatically deleted at the end of your visit. Permanent cookies remain stored on your device until you delete them yourself or they are automatically deleted by your web browser.</span></p>
<p><span style="font-size:11pt;">Cookies from third-party companies may also be stored on your device when you visit our website (third-party cookies). These enable us or you to use certain services of the third-party company (e.g. cookies for processing payment services).</span></p>
<p><span style="font-size:11pt;">Cookies have various functions. Many cookies are technically necessary because certain website functions would not work without them (e.g. the shopping cart function or the display of videos). Other cookies are used to evaluate user behavior or to display advertising.</span></p>
<p><span style="font-size:11pt;">Cookies that are required to carry out the electronic communication process, to provide certain functions you have requested (e.g. for the shopping cart function) or to optimize the website (e.g. cookies to measure the web audience) (necessary cookies) are stored on the basis of Art. 6 Para. 1 lit. f GDPR, unless another legal basis is specified. The website operator has a legitimate interest in storing necessary cookies for the technically error-free and optimized provision of its services. If consent to the storage of cookies and comparable recognition technologies has been requested, processing will take place exclusively on the basis of this consent (Art. 6 Para. 1 lit. a GDPR and Section 25 Para. 1 TTDSG); consent can be revoked at any time.</span></p>
<p><span style="font-size:11pt;">You can set your browser so that you are informed about the setting of cookies and only allow cookies in individual cases, exclude the acceptance of cookies for certain cases or in general and activate the automatic deletion of cookies when closing the browser. If cookies are deactivated, the functionality of this website may be restricted.</span></p>
<p><span style="font-size:11pt;">If cookies are used by third-party companies or for analysis purposes, we will inform you about this separately in this data protection declaration and, if necessary, ask for your consent.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Consent with Usercentrics</span></h3>
<p><span style="font-size:11pt;">This website uses the consent technology from Usercentrics to obtain your consent to the storage of certain cookies on your device or to the use of certain technologies and to document this in compliance with data protection regulations. The provider of this technology is Usercentrics GmbH, Sendlinger Stra&szlig;e 7, 80331 Munich, website:&nbsp;</span><a href="https://usercentrics.com/de/"><u><span style="color:#1155cc;font-size:11pt;">https://usercentrics.com/de/</span></u></a><span style="font-size:11pt;">&nbsp;(hereinafter &quot;Usercentrics&quot;).</span></p>
<p><span style="font-size:11pt;">When you enter our website, the following personal data is transferred to Usercentrics:</span></p>
<ul>
    <li style="list-style-type:disc;font-size:11pt;">
        <p><span style="font-size:11pt;">Your consent(s) or the revocation of your consent(s)</span></p>
    </li>
    <li style="list-style-type:disc;font-size:11pt;">
        <p><span style="font-size:11pt;">Your IP address</span></p>
    </li>
    <li style="list-style-type:disc;font-size:11pt;">
        <p><span style="font-size:11pt;">Information about your browser</span></p>
    </li>
    <li style="list-style-type:disc;font-size:11pt;">
        <p><span style="font-size:11pt;">Information about your device</span></p>
    </li>
    <li style="list-style-type:disc;font-size:11pt;">
        <p><span style="font-size:11pt;">Time of your visit to the website</span></p>
    </li>
</ul>
<p><span style="font-size:11pt;">Furthermore, Usercentrics stores a cookie in your browser in order to be able to assign the consent granted or its revocation to you. The data collected in this way is stored until you ask us to delete it, delete the Usercentrics cookie yourself or the purpose for storing the data no longer applies. Mandatory statutory retention periods remain unaffected.</span></p>
<p><span style="font-size:11pt;">Usercentrics is used to obtain the legally required consent for the use of certain technologies. The legal basis for this is Art. 6 (1) (c) GDPR.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">contact form</span></h3>
<p><span style="font-size:11pt;">If you send us inquiries using the contact form, your details from the inquiry form, including the contact details you provided there, will be stored by us for the purpose of processing the inquiry and in the event of follow-up questions. We will not pass on this data without your consent.</span></p>
<p><span style="font-size:11pt;">This data is processed on the basis of Art. 6 (1) (b) GDPR, provided that your request is related to the fulfillment of a contract or is necessary to carry out pre-contractual measures. In all other cases, the processing is based on our legitimate interest in the effective processing of the requests addressed to us (Art. 6 (1) (f) GDPR) or on your consent (Art. 6 (1) (a) GDPR) if this was requested; the consent can be revoked at any time.</span></p>
<p><span style="font-size:11pt;">The data you enter in the contact form will remain with us until you request deletion, revoke your consent to storage or the purpose for storing the data no longer applies (e.g. after your request has been processed). Mandatory legal provisions - in particular retention periods - remain unaffected.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Inquiry by email, telephone or fax</span></h3>
<p><span style="font-size:11pt;">If you contact us by email, telephone or fax, your request, including all personal data resulting from it (name, request), will be stored and processed by us for the purpose of processing your request. We will not pass on this data without your consent.</span></p>
<p><span style="font-size:11pt;">This data is processed on the basis of Art. 6 (1) (b) GDPR, provided that your request is related to the fulfillment of a contract or is necessary to carry out pre-contractual measures. In all other cases, the processing is based on our legitimate interest in the effective processing of the requests addressed to us (Art. 6 (1) (f) GDPR) or on your consent (Art. 6 (1) (a) GDPR) if this was requested; the consent can be revoked at any time.</span></p>
<p><span style="font-size:11pt;">The data you send to us via contact requests will remain with us until you request deletion, revoke your consent to storage or the purpose for storing the data no longer applies (e.g. after your request has been processed). Mandatory legal provisions - in particular statutory retention periods - remain unaffected.</span></p>
<h2><span style="font-size:16pt;">5. Social Media</span></h2>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">LinkedInPlugin</span></h3>
<p><span style="font-size:11pt;">This website uses functions of the LinkedIn network. The provider is LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2, Ireland.</span></p>
<p><span style="font-size:11pt;">Every time you access a page on this website that contains LinkedIn functions, a connection is established to LinkedIn servers. LinkedIn is informed that you have visited this website using your IP address. If you click on LinkedIn&apos;s &quot;Recommend button&quot; and are logged into your LinkedIn account, LinkedIn can associate your visit to this website with you and your user account. We would like to point out that as the provider of the pages, we have no knowledge of the content of the transmitted data or its use by LinkedIn.</span></p>
<p><span style="font-size:11pt;">The LinkedIn plug-in is used on the basis of Art. 6 (1) (f) GDPR. The website operator has a legitimate interest in the greatest possible visibility in social media. If a corresponding consent has been requested, the processing is carried out exclusively on the basis of Art. 6 (1) (a) GDPR and Section 25 (1) TTDSG, insofar as the consent includes the storage of cookies or access to information on the user&apos;s device (e.g. device fingerprinting) within the meaning of the TTDSG. The consent can be revoked at any time.</span></p>
<p><span style="font-size:11pt;">The data transfer to the USA is based on the standard contractual clauses of the EU Commission. Details can be found here:&nbsp;</span><a href="https://www.linkedin.com/help/linkedin/answer/62538/datenubertragung-aus-der-eu-dem-ewr-und-der-schweiz?lang=de"><u><span style="color:#1155cc;font-size:11pt;">https://www.linkedin.com/help/linkedin/answer/62538/datenubertragung-aus-der-eu-dem-ewr-und-der-schweiz?lang=de</span></u></a></p>
<p><span style="font-size:11pt;">For more information, please see LinkedIn&rsquo;s privacy policy at:&nbsp;</span><a href="https://www.linkedin.com/legal/privacy-policy"><u><span style="color:#1155cc;font-size:11pt;">https://www.linkedin.com/legal/privacy-policy</span></u></a><span style="font-size:11pt;">&nbsp;.</span></p>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">XING Plugin</span></h3>
<p><span style="font-size:11pt;">This website uses functions of the XING network. The provider is New Work SE, Dammtorstra&szlig;e 30, 20354 Hamburg, Germany.</span></p>
<p><span style="font-size:11pt;">Every time you access one of our pages that contains XING functions, a connection is established to XING servers. To our knowledge, no personal data is stored. In particular, no IP addresses are stored and no user behavior is evaluated.</span></p>
<p><span style="font-size:11pt;">The data is stored and analyzed on the basis of Art. 6 (1) (f) GDPR. The website operator has a legitimate interest in the greatest possible visibility in social media. If a corresponding consent has been requested, the processing is carried out exclusively on the basis of Art. 6 (1) (a) GDPR and Section 25 (1) TTDSG, insofar as the consent includes the storage of cookies or access to information on the user&apos;s device (e.g. device fingerprinting) within the meaning of the TTDSG. The consent can be revoked at any time.</span></p>
<p><span style="font-size:11pt;">Further information on data protection and the XING Share button can be found in XING&rsquo;s privacy policy at:&nbsp;</span><a href="https://www.xing.com/app/share?op=data_protection"><u><span style="color:#1155cc;font-size:11pt;">https://www.xing.com/app/share?op=data_protection</span></u></a><span style="font-size:11pt;">&nbsp;.</span></p>
<h2><span style="font-size:16pt;">6. Analysis tools and advertising</span></h2>
<h3><span style="color:#434343;font-size:13.999999999999998pt;">Google Analytics</span></h3>
<p><span style="font-size:11pt;">This website uses functions of the web analysis service Google Analytics. The provider is Google Ireland Limited (&quot;Google&quot;), Gordon House, Barrow Street, Dublin 4, Ireland.</span></p>
<p><span style="font-size:11pt;">Google Analytics enables the website operator to analyze the behavior of website visitors. The website operator receives various usage data, such as page views, length of stay, operating systems used and origin of the user. This data is assigned to the respective end device of the user. There is no assignment to a device ID.</span></p>
<p><span style="font-size:11pt;">Furthermore, Google Analytics allows us to record your mouse and scroll movements and clicks, among other things. Furthermore, Google Analytics uses various modeling approaches to supplement the collected data sets and uses machine learning technologies in data analysis.</span></p>
<p><span style="font-size:11pt;">Google Analytics uses technologies that enable the recognition of the user for the purpose of analyzing user behavior (e.g. cookies or device fingerprinting). The information collected by Google about the use of this website is usually transferred to a Google server in the USA and stored there.</span></p>
<p><span style="font-size:11pt;">The use of this service is based on your consent in accordance with Art. 6 (1) (a) GDPR and Section 25 (1) TTDSG. The consent can be revoked at any time.</span></p>
<p><span style="font-size:11pt;">The data transfer to the USA is based on the standard contractual clauses of the EU Commission. Details can be found here:&nbsp;</span><a href="https://privacy.google.com/businesses/controllerterms/mccs/"><u><span style="color:#1155cc;font-size:11pt;">https://privacy.google.com/businesses/controllerterms/mccs/</span></u></a><span style="font-size:11pt;">&nbsp;.</span></p>
<h4><span style="color:#666666;font-size:12pt;">Browser plug-in</span></h4>
<p><span style="font-size:11pt;">You can prevent Google from collecting and processing your data by downloading and installing the browser plug-in available under the following link:&nbsp;</span><a href="https://tools.google.com/dlpage/gaoptout?hl=de"><u><span style="color:#1155cc;font-size:11pt;">https://tools.google.com/dlpage/gaoptout?hl=de</span></u></a><span style="font-size:11pt;">&nbsp;.</span></p>
<p><span style="font-size:11pt;">For more information about how Google Analytics handles user data, please see Google&rsquo;s privacy policy:&nbsp;</span><a href="https://support.google.com/analytics/answer/6004245?hl=de"><u><span style="color:#1155cc;font-size:11pt;">https://support.google.com/analytics/answer/6004245?hl=de</span></u></a><span style="font-size:11pt;">&nbsp;.</span></p>
<p><br></p>
<p><br></p>`



function DataProtection() {
    return (
        <div dangerouslySetInnerHTML={{__html:dataprotection}} className="flex flex-col justify-start items-start gap-5 px-5 md:px-[20%] pt-10 text-2xl text-black/80 w-full h-full overflow-y-auto">
 

    </div>
    );
}

export default DataProtection;